finish tagprep

diff --git a/.github/workflows/release-quickstart.yml b/.github/workflows/release-quickstart.yml
--- a/.github/workflows/release-quickstart.yml
+++ b/.github/workflows/release-quickstart.yml
@@ -1,3 +1,4 @@
+name: Release Quickstart Workflow
 on:
   pull_request_target:
     types:
@@ -9,13 +10,25 @@ on:
 
 jobs:
   release-quickstart:
+    name: Release Quickstart Job
+    # when the ref is release-next the label "quickstartrelease" must be present on the PR for this job to run, and when
+    # the ref is a release branch the label is not required
     if: |
       github.event.pull_request.merged == true
-      && contains(github.event.pull_request.labels.*.name, 'quickstartrelease')
+      && (
+        github.ref != 'refs/heads/release-next'
+        || contains(github.event.pull_request.labels.*.name, 'quickstartrelease')
+      )
     runs-on: ubuntu-latest
     env:
       ZITI_QUICKSTART_TAG:   ${{ inputs.ziti-quickstart-version || github.event.inputs.ziti-quickstart-version }}
       ZITI_QUICKSTART_IMAGE: ${{ vars.ZITI_QUICKSTART_IMAGE || 'docker.io/openziti/quickstart' }}
+      # use github.ref, not github.head_ref, because this workflow should only run on merged PRs in the target/base
+      # branch context, not the PR source branch
+      GITHUB_REF:            ${{ github.ref }}
+      # user github.sha, not github.pull_request.head.sha, because this workflow should only run on merged PRs in the
+      # target/base branch, not the PR source branch
+      GITHUB_SHA:            ${{ github.sha }}
     steps:
       - name: Debug action
         uses: hmarr/debug-action@v2.1.0
@@ -25,32 +38,6 @@ jobs:
 
       - name: Install Ziti CI
         uses: openziti/ziti-ci@v1
-
-      - name: Compute the Ziti Quickstart Version String
-        id: get_version
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-          GITHUB_REF: ${{ github.ref }}
-          GITHUB_SHA: ${{ github.event.pull_request.head.sha || github.sha }}
-        run: |
-          ZITI_VERSION="$($(go env GOPATH)/bin/ziti-ci -q get-current-version)"
-          # drop the leading 'v', if any
-          ZITI_VERSION=${ZITI_VERSION#v}
-          if ! [[ "${ZITI_VERSION}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
-            # fail the job because we could not obtain the current version from ziti-ci
-            echo "ERROR: ZITI_VERSION=${ZITI_VERSION} is not a semver"
-            exit 1
-          elif [[ "${GITHUB_REF}" =~ ^refs/heads/(release-v[0-9]+\.[0-9]+\.x|main)$ ]]; then
-            # Set output parameters for release branches
-            echo "DEBUG: ZITI_VERSION=${ZITI_VERSION}"
-            echo ZITI_VERSION="${ZITI_VERSION}" >> $GITHUB_OUTPUT
-          else
-            # Append short sha for non-release refs to identify Jenkins smoketest runs and quickstart docker images
-            # shipped from release-next
-            ZITI_VERSION="${ZITI_VERSION}-$(git rev-parse --short ${GITHUB_SHA})"
-            echo "DEBUG: ZITI_VERSION=${ZITI_VERSION}"
-            echo ZITI_VERSION="${ZITI_VERSION}" >> $GITHUB_OUTPUT
-          fi
 
       - name: Set Up QEMU
         uses: docker/setup-qemu-action@v2
@@ -69,17 +56,41 @@ jobs:
           username: ${{ vars.DOCKER_HUB_API_USER || secrets.DOCKER_HUB_API_USER }}
           password: ${{ secrets.DOCKER_HUB_API_TOKEN }}
 
+      - name: Compute the Ziti Quickstart Version String
+        id: get_version
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        run: |
+          QUICKSTART_VERSION="$($(go env GOPATH)/bin/ziti-ci -q get-current-version)"
+          # drop the leading 'v', if any
+          QUICKSTART_VERSION=${QUICKSTART_VERSION#v}
+          if ! [[ "${QUICKSTART_VERSION}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
+            # fail the job because we could not obtain the current version from ziti-ci
+            echo "ERROR: QUICKSTART_VERSION=${QUICKSTART_VERSION} is not a semver"
+            exit 1
+          elif [[ "${GITHUB_REF}" =~ ^refs/heads/(release-v[0-9]+\.[0-9]+\.x|main)$ ]]; then
+            # Set output parameters for release branches
+            echo "DEBUG: QUICKSTART_VERSION=${QUICKSTART_VERSION}"
+            echo QUICKSTART_VERSION="${QUICKSTART_VERSION}" >> $GITHUB_OUTPUT
+          else
+            # Append short sha for non-Ziti-release refs to identify quickstart docker images
+            # shipped from release-next
+            QUICKSTART_VERSION="${QUICKSTART_VERSION}-$(git rev-parse --short ${GITHUB_SHA})"
+            echo "DEBUG: QUICKSTART_VERSION=${QUICKSTART_VERSION}"
+            echo QUICKSTART_VERSION="${QUICKSTART_VERSION}" >> $GITHUB_OUTPUT
+          fi
+
       # This container differs in that :latest is pushed from branch release-next in addition to main and hotfix
       # branches like releasev1.2.x. See https://github.com/openziti/ziti/issues/898
       - name: Configure Quickstart Container
         env:
           IMAGE_REPO: ${{ env.ZITI_QUICKSTART_IMAGE }}
-          IMAGE_TAG: ${{ env.ZITI_QUICKSTART_TAG }}
+          IMAGE_TAG:  ${{ steps.get_version.outputs.QUICKSTART_VERSION }}
         id: tagprep_qs
         run: |
           DOCKER_TAGS=""
           DOCKER_TAGS="${IMAGE_REPO}:${IMAGE_TAG}"
-          if [[ "${{ github.ref }}" =~ ^refs/heads/(release-(next|v[0-9]+\.[0-9]+\.x)|main)$ ]]; then
+          if [[ "${GITHUB_REF}" =~ ^refs/heads/(release-(next|v[0-9]+\.[0-9]+\.x)|main)$ ]]; then
             DOCKER_TAGS+=",${IMAGE_REPO}:latest"
           fi
           echo "DEBUG: DOCKER_TAGS=${DOCKER_TAGS}"
@@ -100,7 +111,7 @@ jobs:
           platforms: linux/amd64,linux/arm64
           tags: ${{ steps.tagprep_qs.outputs.DOCKER_TAGS }}
           build-args: |
-            ZITI_VERSION_OVERRIDE=${{ env.ZITI_VERSION_OVERRIDE }}
+            ZITI_VERSION_OVERRIDE=${{ steps.tagprep_qs.outputs.ZITI_VERSION_OVERRIDE }}
           push: true
 
       - name: Manage Quickstart Latest Tag
@@ -108,6 +119,6 @@ jobs:
         with:
           name: quickstart-latest
           state: present
-          from: ${{ github.ref }}
+          from: ${{ env.GITHUB_SHA }}
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
